version: '3'
services:
  server:
    depends_on:
      - mysql
    build: .
    environment:
      - DATABASE_HOSTNAME=mysql
      - DATABASE_NAME=vapor_auth
      - DATABASE_USER=vapor
      - DATABASE_PASSWORD=password
      - GOOGLE_CALLBACK_URL=http://localhost:8080/google-complete
      - GOOGLE_CLIENT_ID=59264327221-9rnkjq6ed2q1sn73u6bd0pnfcin3ghr0.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=MsWw1L_rzGAJCZslzzvcjLF3
  mysql:
    image: "mysql"
    environment:
      - DATABASE_HOSTNAME=mysql
      - DATABASE_NAME=vapor_auth
      - DATABASE_USER=vapor
      - DATABASE_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
